apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: istio-ingressgateway-certs-alpha
  namespace: istio-system
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  secretName: istio-ingressgateway-certs-alpha
  issuerRef:
    name: letsencrypt-istio
    kind: ClusterIssuer
  commonName: alpha.istio-poc.awx.onl
  dnsNames:
  - alpha.istio-poc.awx.onl