apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: charlie
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: production
  source:
    path: appservices/domain/multiversion/charlie
    repoURL: https://github.com/riveryc/argo-stack.git
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: istio
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true