apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-transaction-service-gcp-sg
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: dev
  source:
    path: service-template
    repoURL: https://github.com/awx-zorian/argo-stack.git
    targetRevision: HEAD
    helm:
      valueFiles:
        - ../service-values/app-transaction-service/values.yaml
        - ../service-values/app-transaction-service/dev/values.yaml
        - ../service-values/app-transaction-service/dev/gcp-sg-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
    