apiVersion: v1
data:
  context: |
    argocdUrl: https://argocd.poc.awx.onl
  service.slack: |
    token: $slack-token
  trigger.sync-operation-change: |
    - when: app.status.operationState.phase in ['Succeeded']
      send: [app-sync-status]
    - when: app.status.operationState.phase in ['Running']
      send: [app-sync-status]
    - when: app.status.operationState.phase in ['Error', 'Failed']
      send: [app-sync-status]
  template.app-sync-status: |
    message: |
      Application {{.app.metadata.name}} sync is {{.app.status.sync.status}}.
      Application details: {{.context.argocdUrl}}/applications/{{.app.metadata.name}}.
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: argo-notifications
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: argocd-notifications
    app.kubernetes.io/version: 1.1.1
    helm.sh/chart: argocd-notifications-1.4.0
  name: argocd-notifications-cm
  namespace: infra
