apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-applicationset
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infra
  source:
    chart: argocd-applicationset
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: '0.1.3'
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true