apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infra
  destination:
    namespace: ingress-nginx
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://kubernetes.github.io/ingress-nginx'
    targetRevision: '3.23.0'
    chart: ingress-nginx
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true