apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-native-rollout-experiment
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: staging
  source:
    path: appservices/domain/native-rollout-experiment
    repoURL: https://github.com/riveryc/argo-stack.git
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: native-rollout-experiment
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true