
serviceName: app-draftpayment-service
servicePort: 10041

image:
  repository: asia.gcr.io/airwallex/draft-service
  tag:

replicaCount: 3

cloudProvider:
  platform:
  region:

resources:
  limits:
    cpu: 2500m
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 1Gi

environment:

secretEnvironment: